name: Check PR Size

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-size:
    uses: ./.github/workflows/_check-diff.yml
    with:
      threshold_lines: 100
      exclude_patterns: "./*.lock"
